name: Testint API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv 
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc dvc-gdrive
          pip install -r requirements.txt
      - name: Test API 
        run: | 
          python utilities/generate_key.py
          export GDRIVE_CREDENTIALS_DATA=$(python utilities/setter.py)
          dvc remote modify model-track gdrive_service_account_json_file_path credentials.json
          dvc remote modify model-track gdrive_service_account_user_email 'benitognet@gmail.com'
          dvc pull model/model.pkl -r model-track
          pytest test/test.py