name: Testint API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: acctions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv 
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc 
          pip install -r requirements.txt
      - name: Test API 
        run: | 
          dvc pull model/model.pkl -r model-track
          pytest test/test.py